# ~/.config/starship.toml

# Since this is always run in Container mode, then no need to waste screen space
[container]
symbol = '⬢'
style ='bold blue dimmed'
format = '[$symbol$env_value]($style) '
# disabled = true

